//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.09 at 02:11:12 PM EST 
//


package edu.yale.cs.hadoopdb.catalog.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.yale.cs.hadoopdb.catalog.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DBClusterConfiguration_QNAME = new QName("http://edu.yale.cs.db.hadoop/DBConfigurationSchema", "DBClusterConfiguration");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.yale.cs.db.hadoop.db.configuration
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Relation }
     * 
     */
    public Relation createRelation() {
        return new Relation();
    }

    /**
     * Create an instance of {@link Configuration }
     * 
     */
    public Configuration createConfiguration() {
        return new Configuration();
    }

    /**
     * Create an instance of {@link Node }
     * 
     */
    public Node createNode() {
        return new Node();
    }

    /**
     * Create an instance of {@link Partition }
     * 
     */
    public Partition createPartition() {
        return new Partition();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Configuration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://edu.yale.cs.db.hadoop/DBConfigurationSchema", name = "DBClusterConfiguration")
    public JAXBElement<Configuration> createDBClusterConfiguration(Configuration value) {
        return new JAXBElement<Configuration>(_DBClusterConfiguration_QNAME, Configuration.class, null, value);
    }

}
